/**
 * Postcard service — daily social-format capture-card.
 *
 * Sibling to the Diary feature, deliberately split. Diary = long-form,
 * private, reflective journal entries. Postcard = short, public,
 * photo-first social card the user can edit + share to
 * Instagram / TikTok / Twitter.
 *
 * What a Postcard is:
 *   - 2-4 of TODAY's photos arranged in a collage
 *   - 1-2 line caption in the cat's voice (editable by the user)
 *   - Tasteful "🐾 catmd.pet" watermark in a corner
 *   - Captured as 1080×1080 (square) or 1080×1920 (story) PNG
 *   - Shared via the native share sheet
 *
 * Photo sources for the collage (today's local-date window):
 *   - The cat profile photo IF updated today
 *   - Scan image_uri from any scan run today
 *   - symptom_photo health events from today
 *   (Diary's photoUri is NOT used here — diary is text-only now.)
 *
 * Caption generation: same LLM stack as diary but with a TIGHTLY
 * constrained prompt (1-2 sentences max, must read as a quotable
 * Instagram caption, must work standalone without the diary's
 * extended cat-voice context).
 *
 * Cost: ~$0.0002 per caption. Trivial.
 */
import * as FileSystem from 'expo-file-system/legacy';
import { completeJson } from '../ai/client';
import { ARCHETYPE_META, type PersonalityArchetype } from './personality';
import type { CatProfile } from '../state/catStore';
import type { PhotoStudioPhoto } from './photoStudio';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A single photo entry in the postcard collage. */
export type PostcardPhoto = {
  /** Local file:// URI on the device. */
  uri: string;
  /**
   * Where this photo came from — surfaced in analytics + future UX.
   * `gallery` is the new canonical source (Bond's hero photo capture).
   * `profile` covers the legacy fallback for cats whose photo was
   * uploaded before the gallery existed AND was the only thing
   * available for the postcard. `scan` / `symptom_photo` are kept as
   * type variants but no longer populated by `gatherTodaysPhotos` — they
   * exist so old cached postcards still type-check.
   */
  source: 'gallery' | 'profile' | 'scan' | 'symptom_photo';
  /** ISO timestamp the photo was attached/captured. */
  captured_at: string;
  /**
   * Pixel dimensions of the original photo. Used by the collage layout
   * picker to match each photo to a cell with a similar aspect ratio
   * (so we tile 3 portraits as 3 columns, 3 landscapes as 3 stripes,
   * 1 landscape + 2 portraits as a wide-top + split-bottom layout, etc.)
   * — and to pick `cover` vs `contain` per cell so we minimise the
   * dark blurred-backdrop fill that Android's captureRef rendered too
   * dark on share. Optional because old cached postcards don't have it
   * (they fall back to the legacy 3-stripe layout, which is fine — the
   * day they're regenerated with v3+ they'll get the new tiling).
   */
  width?: number;
  height?: number;
};

export type Postcard = {
  id: string;
  cat_id: string;
  date: string;          // YYYY-MM-DD local
  caption: string;       // editable; starts as AI-generated
  caption_ai_original: string; // the original AI version (for "reset to AI" UX + funnel signal)
  photos: PostcardPhoto[];
  generated_at: string;
  model: string;
  /**
   * Single mood word produced by the captioner (e.g. "regal", "smug",
   * "playful", "sleepy"). Used for matching trending-audio suggestions
   * in the share flow. Optional because postcards generated before this
   * field landed don't have it.
   */
  mood_word?: string;
  /**
   * Prompt version that produced this caption. Used to silently
   * migrate stale postcards on Postcard screen mount — captions
   * generated by the v1 prompt are long and journal-style ("Today, I
   * observed the world..."), which the v2 prompt (2026-05-02) forbids.
   * Bumping this number triggers a one-shot auto-regen on next view.
   *
   *   1 = original prompt (long, "Today, I..." failures common)
   *   2 = 2026-05-02 prompt (≤12 words, no temporal openers)
   *
   * Postcards with `undefined` are treated as v1.
   */
  caption_prompt_version?: number;
};

/** The current postcard caption prompt version. Bump on every prompt
 *  rewrite so cached postcards auto-migrate on next view. */
export const POSTCARD_CAPTION_PROMPT_VERSION = 3;

// ---------------------------------------------------------------------------
// Photo aggregator
// ---------------------------------------------------------------------------

function localDateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Pull today's photos from the photo gallery (the canonical source).
 * Postcard collages are deliberately built from the user's curated
 * gallery — NOT from triage scan or symptom photos, which are medical
 * context and inappropriate for social posts.
 *
 * `gatherTodaysPhotos` returns up to `max` photos (default 4) sorted
 * newest-first. Returns an empty array if nothing was captured today;
 * caller should surface the "snap a photo" empty state.
 *
 * Legacy cat profile photo: if the gallery is empty AND the cat's
 * profile photo was updated today, we use that as a single-source
 * fallback. Covers the edge case where a long-running user updated
 * their profile photo today but hasn't yet adopted the gallery flow.
 */
export function gatherTodaysPhotos(opts: {
  cat: CatProfile;
  galleryToday: PhotoStudioPhoto[]; // newest-first; today's photos only
  max?: number;
}): PostcardPhoto[] {
  const { cat, galleryToday, max = 3 } = opts;

  if (galleryToday.length > 0) {
    // RANDOMISED selection. Daily photo cap was removed 2026-05-04 —
    // users now take unlimited photos. To give the postcard collage a
    // fresh feel each generation (and so the postcard doesn't always
    // show the SAME 3 chronologically-newest photos), we sample at
    // random from the day's pool. Using Fisher-Yates so every photo
    // has equal probability of selection regardless of capture order.
    //
    // Date-seeding is deliberately NOT used here — we want the
    // collage to vary across regenerations within the same day (the
    // user can re-roll a postcard if they don't love the first take).
    // Cross-day diversity falls out for free since the pool changes.
    const pool = [...galleryToday];
    for (let i = pool.length - 1; i > 0; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = pool[i]!;
      pool[i] = pool[j]!;
      pool[j] = tmp;
    }
    return pool.slice(0, max).map((p) => ({
      uri: p.uri,
      source: 'gallery' as const,
      captured_at: p.added_at,
      // Carry pixel dims so the share-card layout can pick orientation-
      // aware tiling. Both fields are optional on PhotoStudioPhoto so
      // we conditionally spread to avoid setting `undefined` keys.
      ...(p.width != null ? { width: p.width } : {}),
      ...(p.height != null ? { height: p.height } : {}),
    }));
  }

  // Fallback: profile photo if it was updated today.
  const today = new Date();
  const todayKey = localDateKey(today);
  const isUpdatedToday = (iso: string | null | undefined) => {
    if (!iso) return false;
    try {
      return localDateKey(new Date(iso)) === todayKey;
    } catch {
      return false;
    }
  };
  if (cat.photo_uri && isUpdatedToday(cat.updated_at)) {
    return [
      {
        uri: cat.photo_uri,
        source: 'profile' as const,
        captured_at: cat.updated_at ?? new Date().toISOString(),
      },
    ];
  }

  return [];
}

// ---------------------------------------------------------------------------
// Caption generation
// ---------------------------------------------------------------------------

const VOICE_RULES = `You are writing a punchy social-media caption from a cat's POV. The user will paste it onto an Instagram / TikTok post alongside a photo collage. The caption must be SHORT, QUOTABLE, and make people stop scrolling.

HARD RULES (violate any of these and the output is wrong):
- ONE sentence. Not two. Not "X. Y." — ONE.
- 12 WORDS MAXIMUM. Aim for 4-8.
- NEVER start with "Today" or any temporal opener ("This morning", "Yesterday" etc).
- NEVER write like a diary or journal entry. This is a quotable line, not a recap.
- NEVER literally describe the photo ("look at me sitting", "here I am").
- NEVER use generic adjectives ("discerning", "peculiar", "whimsical", "magical"). Specific > flowery.
- NO emojis. NO hashtags. NO capital-letter all-caps shouting.
- Cat-voice, first person. SWAG ENERGY: imperious, judgmental, slightly disdainful, smug. Confident bordering on arrogant. NEVER baby-talk, NEVER "uwu", NEVER polite, NEVER apologetic.
- FORBIDDEN PHRASES that immediately kill the voice: "I appreciate", "thank you", "I find joy", "of course", "I love", "such a", "so much". If your draft contains any of these — start over.

WHAT WORKS (calibrate to this register — do NOT copy these literally):

"Status: regal."
"The bird at the window was unreasonable."
"Won."
"Negotiated terms with the windowsill."
"We do not chase. We cause."
"Day 14 of training the human."
"The blanket and I have an understanding."
"I have decided the green chair is, finally, mine."
"Three feints, one capture. Correct pace."
"Demanded fealty. Received it."
"Supervised."
"The bath water has betrayed me."
"Reviewed the household. Verdict: tolerable."

WHAT DOES NOT WORK (these are immediate failures):

❌ "Today, I observed the world with a discerning eye, noting the peculiarities of my realm."
   → Too long, starts with "Today", journal-style, generic adjectives.
❌ "Look at this adorable photo of Mittens napping on the couch."
   → Describes the photo literally, baby-talk register.
❌ "Such a cute kitty day! 🐱✨ #catsofinstagram"
   → Emojis, hashtags, generic.
❌ "Hey friends! Just wanted to share what I've been up to today..."
   → Conversational diary opener.

Aim: an aphorism, a verdict, a deadpan observation. The kind of line someone would screenshot and send to a friend.

Output JSON with two fields:
  - "caption": ONE sentence, ≤12 words, in the cat's voice
  - "mood_word": one single word capturing today's mood (e.g. "regal", "smug", "playful", "sleepy")`;

function buildCaptionUserPrompt(opts: {
  catName: string;
  photoCount: number;
  archetype: PersonalityArchetype | null;
  hasCheckin: boolean;
  hasScan: boolean;
  hasReadCat: boolean;
  weekday: string;
  /** Most recent check-in mood (today): "happy" / "normal" / "off". */
  todaysMood?: string | null;
  /** Body language observation tags from today's Read session. */
  bodyLanguageTags?: string[];
  /**
   * Streak-day milestone hit today (7 / 14 / 30 / 60 / 90 / 180 / 365)
   * or null. Postcards on milestone days lean celebratory.
   */
  streakMilestone?: number | null;
  /** True if today is the cat's birthday. Caption may riff on it. */
  isBirthday?: boolean;
  /** True if today is the cat's adoption-iversary. */
  isAdoptionIversary?: boolean;
}): string {
  const {
    catName,
    photoCount,
    archetype,
    hasCheckin,
    hasScan,
    hasReadCat,
    weekday,
    todaysMood,
    bodyLanguageTags,
    streakMilestone,
    isBirthday,
    isAdoptionIversary,
  } = opts;

  const lines: string[] = [];
  lines.push(`Cat name: ${catName}.`);
  lines.push(`Today is ${weekday}.`);
  lines.push(`Number of photos in today's collage: ${photoCount}.`);

  if (archetype) {
    const meta = ARCHETYPE_META[archetype];
    lines.push(`Personality archetype: ${meta.name} — ${meta.oneLiner}`);
  }

  if (todaysMood) {
    lines.push(`Today's check-in mood: ${todaysMood}.`);
  }

  if (bodyLanguageTags && bodyLanguageTags.length > 0) {
    // Cap so the prompt doesn't bloat from a chatty observation.
    const capped = bodyLanguageTags.slice(0, 5).join(', ');
    lines.push(`Body language tags from today's Read session: ${capped}.`);
  }

  if (isBirthday) {
    lines.push(`SPECIAL: today is ${catName}'s BIRTHDAY. The caption may lean celebratory but stay quotable.`);
  } else if (isAdoptionIversary) {
    lines.push(`SPECIAL: today is the anniversary of when ${catName} joined the household. Lean reflective + warm.`);
  } else if (streakMilestone) {
    lines.push(`SPECIAL: ${streakMilestone}-day check-in streak landed today. The caption may acknowledge the rhythm — "day ${streakMilestone}" energy.`);
  }

  const dayBits: string[] = [];
  if (hasCheckin) dayBits.push('a daily check-in was logged');
  if (hasScan) dayBits.push('a triage scan was run');
  if (hasReadCat) dayBits.push(`a body-language read was recorded`);
  if (dayBits.length > 0) {
    lines.push(`Notable events today: ${dayBits.join(', ')}.`);
  }

  lines.push('');
  lines.push('Write the caption. JSON only.');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Read a local file:// URI as base64. Best-effort — returns null on any
 * failure so the caption still generates without the photo reference.
 */
async function fileUriToBase64(uri: string | null | undefined): Promise<string | null> {
  if (!uri) return null;
  if (!uri.startsWith('file://') && !uri.startsWith('/')) return null;
  try {
    return await FileSystem.readAsStringAsync(uri, {
      encoding: FileSystem.EncodingType.Base64,
    });
  } catch {
    return null;
  }
}

const WEEKDAYS = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];

/**
 * Generate today's postcard for the cat. Pulls together the day's
 * photos + an AI-generated short caption. The caller is responsible
 * for surfacing the result + the editable caption field.
 *
 * Throws on AI errors — caller catches and shows a retry CTA.
 */
export async function generatePostcard(opts: {
  cat: CatProfile;
  photos: PostcardPhoto[];
  archetype: PersonalityArchetype | null;
  hasCheckinToday: boolean;
  hasScanToday: boolean;
  hasReadCatToday: boolean;
  /** Today's most-recent check-in mood word ("happy" / "normal" / "off"). */
  todaysMood?: string | null;
  /** Body-language observation tags from today's Read session, if any. */
  bodyLanguageTags?: string[];
  /** Streak milestone landed today (7 / 14 / 30 / 60 / 90 / 180 / 365). */
  streakMilestone?: number | null;
  /** True if today is the cat's birthday. */
  isBirthday?: boolean;
  /** True if today is the adoption-iversary. */
  isAdoptionIversary?: boolean;
}): Promise<Postcard> {
  const {
    cat,
    photos,
    archetype,
    hasCheckinToday,
    hasScanToday,
    hasReadCatToday,
    todaysMood,
    bodyLanguageTags,
    streakMilestone,
    isBirthday,
    isAdoptionIversary,
  } = opts;

  const today = new Date();
  const weekday = WEEKDAYS[today.getDay()] ?? 'Today';

  // Vision: attach the first photo if available so the model has SOME
  // sense of the day's visual mood. Best-effort — fall through if the
  // base64 read fails.
  const referenceBase64 = photos.length > 0 ? await fileUriToBase64(photos[0]?.uri) : null;

  const user = buildCaptionUserPrompt({
    catName: cat.name,
    photoCount: photos.length,
    archetype,
    hasCheckin: hasCheckinToday,
    hasScan: hasScanToday,
    hasReadCat: hasReadCatToday,
    weekday,
    ...(todaysMood !== undefined ? { todaysMood } : {}),
    ...(bodyLanguageTags ? { bodyLanguageTags } : {}),
    ...(streakMilestone !== undefined ? { streakMilestone } : {}),
    ...(isBirthday !== undefined ? { isBirthday } : {}),
    ...(isAdoptionIversary !== undefined ? { isAdoptionIversary } : {}),
  });

  type LlmResult = { caption: string; mood_word: string };

  const result = await completeJson<LlmResult>({
    activity: 'postcard_caption',
    system: VOICE_RULES,
    user,
    imageBase64: referenceBase64,
    imageDetail: 'low',
    temperature: 0.8,    // higher than diary's 0.85 isn't safe (long output);
                         // 0.8 keeps output punchy + lets the model find a
                         // surprising aphoristic angle vs returning the same
                         // safe phrasing every time.
    maxTokens: 80,       // hard ceiling so the model can't write a paragraph
                         // even if it wanted to. 12-word caption ≈ 30 tokens
                         // + JSON wrapper + mood_word ≈ 50 tokens; 80 has
                         // headroom but blocks essay-length drift.
    jsonSchema: {
      name: 'cat_postcard_caption',
      strict: true,
      schema: {
        type: 'object',
        additionalProperties: false,
        required: ['caption', 'mood_word'],
        properties: {
          caption: { type: 'string' },
          mood_word: { type: 'string' },
        },
      },
    },
  });

  const caption = result.caption.trim();
  const moodWord = (result.mood_word ?? '').trim().toLowerCase() || undefined;

  return {
    id: `pc_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 6)}`,
    cat_id: cat.id,
    date: localDateKey(today),
    caption,
    caption_ai_original: caption,
    photos,
    generated_at: new Date().toISOString(),
    model: process.env.EXPO_PUBLIC_AI_MODEL ?? 'gpt-4o-mini',
    caption_prompt_version: POSTCARD_CAPTION_PROMPT_VERSION,
    ...(moodWord ? { mood_word: moodWord } : {}),
  };
}

/** Date key helper for store cache keys. */
export function todayKey(): string {
  return localDateKey(new Date());
}
